# Generated by CGPT
# Use a base image with Java 19
FROM openjdk:19-jdk

# Set the working directory in the container
WORKDIR /app

# Copy the Spring Boot JAR file into the container
COPY target/italy-municipalities-rest.jar /app/italy-municipalities-rest.jar

# Expose the port your Spring Boot app is listening on (default is 8080)
EXPOSE 8080

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "italy-municipalities-rest.jar"]
